name: "envoy-example"
services:
  proxy:
    image: "bitnami/envoy:latest"
    restart: always
    volumes:
      - "./envoy.yaml:/opt/bitnami/envoy/conf/envoy.yaml"
    ports:
      - "8080:8080"
      - "9901:9901"
    networks:
      - app-network

  api_server:
    image: "node:latest"
    restart: always
    command: "node /app/server.js"
    volumes:
      - "./server.js:/app/server.js"
#    ports:
#      - "8081:8080"
    networks:
      - app-network

networks:
  app-network: